name: get_light_example
description: Example app for the get_light package.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  get_light:
    path: ../
